services:
  - type: web
    name: farmacia-pro-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 6543
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: postgres
      - key: DB_SSL
        value: true
      - key: SUPER_ADMIN_EMAIL
        value: joel.miranda2009@gmail.com
      - key: SUPER_ADMIN_PASSWORD
        value: jjma2001
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false